### ISSUE TITLE
Doesn't work with cocoapods

### ISSUE THREAD

**Issue by simonedamico** [HipByte/motion-testflight#11]
If a specify the path of pod, at the end of compilation I get a duplicate symbol error.

**Comment by jonbuffington** [comment]
I am also experiencing this issue after updating a RubyMotion project to use CocoaPods. I get the duplicate symbols error with both TestFlightSDK 1.1 and 1.2beta2.

**Comment by jonbuffington** [comment]
I was able to fix the duplicate symbol issue by changing

from
    `app.testflight.sdk = 'vendor/Pods/TestFlightSDK'`

to
    `app.testflight.sdk = 'vendor/Pods'`

Hope that helps.

**Comment by simonedamico** [comment]
I also have AFNetworking in my Pods and with your fix I get this error: AFNetworking/AFNetworking/AFURLConnectionOperation.m:29:2: error: AFNetworking must be built with ARC.

**Comment by Watson1978** [comment]
hmm, when you would load TestFlightSDK with
  `app.testflight.sdk = 'vendor/Pods/TestFlightSDK'`
and
  `pod 'TestFlightSDK'`
,
looks like TestFlightSDK is linked to your app at two times.

```
$ rake testflight notes='zomg!'
---snip---
duplicate symbol _OBJC_CLASS_$_TFMsgPackDeserializer in:
    /Users/watson/Documents/workspace/TestFlight_CocoaPods/vendor/Pods/TestFlightSDK/libTestFlight.a(TFMsgPackDeserializer.o)
    ./vendor/Pods/TestFlightSDK/libTestFlight.a(TFMsgPackDeserializer.o)
ld: 388 duplicate symbols for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
rake aborted!
Command failed with status (1): [/Applications/Xcode.app/Contents/Developer...]
/Library/RubyMotion/lib/motion/project/builder.rb:386:in `build'
/Library/RubyMotion/lib/motion/project/app.rb:72:in `build'
/Library/RubyMotion/lib/motion/project.rb:56:in `block (2 levels) in <top (required)>'
Tasks: TOP => archive => build:device
(See full trace by running task with --trace)
```

For now, you could avoid this issue when you would remove  `app.testflight.sdk = 'vendor/Pods/TestFlightSDK'` line from Rakefile
