### ISSUE TITLE
Anonymous testflight data

### ISSUE THREAD

**Issue by neiled** [HipByte/motion-testflight#13]
So my app is showing anonymous data in the sessions because we're not setting the UUID before takeoff:
http://help.testflightapp.com/customer/portal/articles/829863-build-activity-is-showing-anonymous-data

Any ideas what the best way would be to solve this? I'm happy to submit a patch if required, if you have any pointers?

Thanks a lot!

**Comment by Watson1978** [comment]
This should be soleved with #16,  it will ship at next update.

Thanks
