### ISSUE TITLE
Online documentation out-of-date after last change

### ISSUE THREAD

**Issue by hickst** [HipByte/motion-testflight#2]
Last GitHub commit says: "Add needed `require 'rubygems'` line to README."
The online article at http://www.rubymotion.com/developer-center/articles/testflight/
should also be updated to reflect this change.

**Comment by chrisradford** [comment]
This was updated about 4 months ago with this commit (https://github.com/HipByte/RubyMotionDocumentation/commit/58fa280113524720d180075ef5f6e653c1e3f58c) so this issue can now be closed.

**Comment by Watson1978** [comment]
Sorry, updates on GITHUB are not reflected in real time, so far.
However, now, there is `require 'rubygems'` at http://www.rubymotion.com/developer-center/articles/testflight/

Thanks
