### ISSUE TITLE
Adding devices to a Provisioning Profile

### ISSUE THREAD

**Issue by sbauch** [HipByte/motion-testflight#22]
Sorry if this is not the right place for this, but I have an issue of confusion.

I'm new to iOS development, so the whole certificate/provisioning profile/devices process was a bit hairy for me to get through.

I was finally able to get my app installed on two friends' devices via testflight.

I now want to allow a third. He registered on testflight and added his device. I exported the device info and added to my Apple Developer account as a device. I then edited my provisioning profile to allow that new device. I downloaded the provisioning profile and uploaded directly to tesflight. This third friend is unable to install the app.

So my question is this:

When I add new devices to an existing provisioning profile, must I change the path to that profile in the Rakefile and deploy a new build to testflight? Or is simply uploading the updated provisioning profile to testflight supposed to allow this new device to install the app?

**Comment by christos** [comment]
@sbauch The provisioning profile is used by RubyMotion's build system and it is embedded inside your app's `.app` bundle as `embedded.mobileprovision`. 

My understanding is that the code signing done after that step prevents Testflight from replacing the embedded profile with the one you've uploaded.

So, in your case, what you need to do is:

Download the updated profile from the provisioning portal and move it to `~/Library/MobileDevice/Provisioning\ Profiles/`

If you have an older profile there (probably one installed by Xcode), you have two options. You can either delete that profile, _or_ point your `Rakefile` to the new profile's path (just the name won't do it seems):

```
 app.provisioning_profile = "~/Library/MobileDevice/Provisioning\ Profiles/<long-hex-here>.mobileprovision"` 
```

Keep in mind that the build system looks for a profile named _`iOS Team Provisioning Profile`_ and it should warn you if your new profile is not called that, then randomly pick the first profile it finds in the directory.

Hope this helps. 

BTW, your options for support are usually, first IRC (#rubymotion on freenode), then the Google group, and if all fails, you can try `motion support` to file a ticket.

**Comment by sbauch** [comment]
thank you for the thorough reply, much appreciated! 

I think you are correct that the code signing prevents Testflight from replacing the embedded profile. 

Not the end of the world, just have to do a new build essentially any time I add new testers.
