### ISSUE TITLE
When will Motion-Testflight support new TestFlight?

### ISSUE THREAD

**Issue by chunlea** [HipByte/motion-testflight#34]
We all know that the new Testfilght is builtin in iTunes Connect, will the motion-testflight support new TestFlight?
Now we can use ApplicationLoader to upload new test version to iTunes Connect.

**Comment by fschwahn** [comment]
The old testflight service will be [discontinued on 2/26/2015](http://help.testflightapp.com/customer/portal/articles/1768754).
Maybe a migration path can be added to the README?

**Comment by fschwahn** [comment]
Ok, as testflight shuts down a week from now, I have searched a bit more and found the following:
https://groups.google.com/forum/#!topic/rubymotion/hv8TXOzigI4

Seems to be pretty easy.

**Comment by franciscomxs** [comment]
+1
