### ISSUE TITLE
rake testflight failed

### ISSUE THREAD

**Issue by siuying** [HipByte/motion-testflight#8]
```
rake testflight notes="debugging"
rake aborted!
Don't know how to build task 'archive:development'
```

it seems this is cause by change of rubymotion tasks

**Comment by Watson1978** [comment]
What version of motion-testflight would you use?
If you use motion-testflight < 1.2, could you update gem?

I think this issue will fixed with
https://github.com/HipByte/motion-testflight/commit/dfb1bcf8af98155179957a30e6b15fd9648f9614

Thank you

**Comment by siuying** [comment]
Thanks! I think the problem is caused by i didnt specify version in Gemfile. this problem do not show now.
