### ISSUE TITLE
rake testflight returns error "can't convert Array into String"

### ISSUE THREAD

**Issue by siuying** [HipByte/motion-testflight#9]
When I install simple-view gems with motion-testflight gem, i see following error:

```
$ rake testflight notes="test testflight upload" --trace
** Invoke testflight (first_time)
** Invoke testflight:submit (first_time)
** Execute testflight:submit
rake aborted!
can't convert Array into String
```

A sample project settings and log files can be find at: https://gist.github.com/3905817

It seems like simple-view add some [arrays of files](https://github.com/seanho/SimpleView/blob/master/lib/simple-view.rb#L11) to app.files where motion-testflight expects [files](https://github.com/HipByte/motion-testflight/blob/master/lib/motion/project/testflight.rb#L73). 

I dont sure which is right, should I report an issue here or on simple-view project?

**Comment by Watson1978** [comment]
hmm, seems simple-view insert file list to `app.files` as array.
https://github.com/seanho/SimpleView/blob/master/lib/simple-view.rb#L11

**Comment by siuying** [comment]
This is a duplicate of #1
